version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    environment:
       POSTGRES_PASSWORD: P@$$w0rd
       SCHEMA: public
    networks:
      - app-network
networks:
  app-network:
    driver: bridge